// Nome:Lucas Bruck; RA:2612259

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lbruck
 */
public class CadAtend extends javax.swing.JFrame {
    
    private Atendente atend1 = new Atendente();
    private GerAtend gerAt = GerAtend.geraAtend();//Reflexividade
    
    private static CadAtend geAtendUnic;
    
    //MÉTODO SINGLETON
    public static CadAtend gerCadAtend(){
        if(geAtendUnic == null){
            geAtendUnic = new CadAtend();
        }
        
        return geAtendUnic;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadAtend.class.getName());

    /**
     * Creates new form FormAtendentes
     */
    public CadAtend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        cxNomeAtend = new javax.swing.JTextField();
        lbCpfAtend = new javax.swing.JLabel();
        cxCpfAtend = new javax.swing.JTextField();
        lbCodAtend = new javax.swing.JLabel();
        cxCodAtend = new javax.swing.JTextField();
        lbEspeciali = new javax.swing.JLabel();
        cxEspec = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAtend = new javax.swing.JTable();
        btAdicionar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        lbCadAtend = new javax.swing.JLabel();
        btAtualizTab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lbNome.setText("Nome Atendente");

        lbCpfAtend.setText("CPF Atendente");

        lbCodAtend.setText("Codigo Atendente");

        lbEspeciali.setText("Especialidade");

        tbAtend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Codigo", "Especialidade"
            }
        ));
        jScrollPane1.setViewportView(tbAtend);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar Pelo CPF");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        lbCadAtend.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        lbCadAtend.setText("Cadastro de Atendnete");

        btAtualizTab.setText("Atualizar tabela");
        btAtualizTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCodAtend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCodAtend))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addGap(18, 18, 18)
                        .addComponent(cxNomeAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCpfAtend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCpfAtend)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEspeciali)
                        .addGap(18, 18, 18)
                        .addComponent(cxEspec))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btAdicionar)
                .addGap(28, 28, 28)
                .addComponent(btBuscar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAtualizTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbCadAtend)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lbCadAtend)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(cxNomeAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCpfAtend)
                    .addComponent(cxCpfAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodAtend)
                    .addComponent(cxCodAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEspeciali)
                    .addComponent(cxEspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btBuscar)
                    .addComponent(btLimpar))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btAtualizTab))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        inseAtend();
        listTab();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        pesquisar();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btAtualizTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizTabActionPerformed
        listTab();
    }//GEN-LAST:event_btAtualizTabActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        limpar();
    }//GEN-LAST:event_formWindowActivated
    public void sair(){
       
                FormPrincipal.telaErroAcao("Deseja realmente sair?", "Saida", this::dispose, 
                () -> FormPrincipal.telaErroAcao("Deseja apagar os dados?", "Dados", this::limpar, null));//Reflexividade

    }
    public void pesquisar(){
        atend1 = new Atendente();
        try{
            atend1.setCpf(Integer.parseInt(cxCpfAtend.getText()));//Reflexividade
            
            atend1 = gerAt.consAtendente(atend1);//Reflexividade
            
            if(atend1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Atendente encontrado com sucesso!\nConfira a tabela",
                        "Consulta de Atendente",
                        JOptionPane.INFORMATION_MESSAGE
                        
                );//Reflexividade
                
                DefaultTableModel modTab = (DefaultTableModel)tbAtend.getModel(); //Reflexividade
                int posLin = 0;
                modTab.setRowCount(posLin);//Reflexividade

                for(Atendente aten : gerAt.getBdAtend()){
                    if (atend1.getCpf() == aten.getCpf()){
                        modTab.insertRow(posLin, new Object[]{aten.getNome(),
                            aten.getCpf(), aten.getCodAtendente(), 
                            aten.getEspecialidade()
                        });//Reflexividade
                        posLin++;
                    }
                }
                
                
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Cpf não encontrado!",
                        "Consulta de Atendente",
                        JOptionPane.QUESTION_MESSAGE
                );//Reflexividade
                cxCodAtend.setText("");//Reflexividade
                cxCodAtend.requestFocus();//Reflexividade
            }
            
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                    null,
                    "O cpf deve ser um número inteiro!",
                    "Consulta de Atendente",
                    JOptionPane.ERROR_MESSAGE
            );//Reflexividade
            cxCpfAtend.setText("");//Reflexividade
            cxCpfAtend.requestFocus();//Reflexividade
        }
    }
    
    public void limpar(){
        cxCodAtend.setText("");//Reflexividade
        cxCpfAtend.setText("");//Reflexividade
        cxEspec.setText("");//Reflexividade
        cxNomeAtend.setText("");//Reflexividade
    }
    public void inseAtend(){
        atend1 = new Atendente();
        
        try{

            atend1.setNome(cxNomeAtend.getText());//Reflexividade
            atend1.setCpf(Integer.parseInt(cxCpfAtend.getText()));//Reflexividade
            atend1.setCodAtendente(Integer.parseInt(cxCodAtend.getText()));//Reflexividade
            atend1.setEspecialidade(cxEspec.getText());//Reflexividade
 
            atend1 = gerAt.insAtendente(atend1);//Reflexividade
            
            if(atend1 != null){
                FormPrincipal.telaErroAcao("Atendente cadastrado com sucesso!\nDeseja Cadastrar outro?", 
                        "Cadastro de Atendenete", this::limpar, this::dispose);//Reflexividade
            }
        }
        catch(EspecialidadeInvalidaException eie){
            eie.impEspecialidadeInvalida();//Reflexividade
            cxEspec.setText("");//Reflexividade
            cxEspec.requestFocus();//Reflexividade
        }
        
    }
    public void listTab(){
            DefaultTableModel modTab = (DefaultTableModel)tbAtend.getModel(); //Reflexividade
            int posLin = 0;
            modTab.setRowCount(posLin);//Reflexividade

            for(Atendente aten : gerAt.getBdAtend()){
                modTab.insertRow(posLin, new Object[]{aten.getNome(),
                    aten.getCpf(), aten.getCodAtendente(),aten.getEspecialidade(),
                });//Reflexividade
                posLin++;
            }
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadAtend().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAtualizTab;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCodAtend;
    private javax.swing.JTextField cxCpfAtend;
    private javax.swing.JTextField cxEspec;
    private javax.swing.JTextField cxNomeAtend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCadAtend;
    private javax.swing.JLabel lbCodAtend;
    private javax.swing.JLabel lbCpfAtend;
    private javax.swing.JLabel lbEspeciali;
    private javax.swing.JLabel lbNome;
    private javax.swing.JTable tbAtend;
    // End of variables declaration//GEN-END:variables
}
