 // Nome:Lucas Bruck; RA:2612259

import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    public static void telaErroInfo(String mensagem, String nomeTela){
        JOptionPane.showMessageDialog(
                        null,
                        mensagem,
                        nomeTela,
                        JOptionPane.INFORMATION_MESSAGE
                );//Reflexividade
    }
    
    public static void telaErroAcao(String mensagem, String NomeTela, Runnable func, 
            Runnable funcEls){
        
        int resp =  JOptionPane.showConfirmDialog(
                null,
                mensagem,
                NomeTela,
                JOptionPane.YES_NO_OPTION
        );//Reflexividade
       if(resp == 0){
           func.run();
           //System.exit(0);
       }
       else{
       funcEls.run();
       }
    }
    
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMenuPrinc = new javax.swing.JLabel();
        barMenu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menCadasAgend = new javax.swing.JMenuItem();
        menCadasAtend = new javax.swing.JMenuItem();
        menCadasClient = new javax.swing.JMenuItem();
        menuRelat = new javax.swing.JMenu();
        menRelatGeral = new javax.swing.JMenuItem();
        menRelatOut = new javax.swing.JMenu();
        menRelatCli = new javax.swing.JMenuItem();
        menRelatAtend = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMenuPrinc.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbMenuPrinc.setText("Menu Principal");

        menuCadastros.setText("Cadastros");

        menCadasAgend.setText("Agendamentos...");
        menCadasAgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadasAgendActionPerformed(evt);
            }
        });
        menuCadastros.add(menCadasAgend);

        menCadasAtend.setText("Atendentes...");
        menCadasAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadasAtendActionPerformed(evt);
            }
        });
        menuCadastros.add(menCadasAtend);

        menCadasClient.setText("Clientes...");
        menCadasClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadasClientActionPerformed(evt);
            }
        });
        menuCadastros.add(menCadasClient);

        barMenu.add(menuCadastros);

        menuRelat.setText("Relatorios");

        menRelatGeral.setText("Geral...");
        menRelatGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelatGeralActionPerformed(evt);
            }
        });
        menuRelat.add(menRelatGeral);

        menRelatOut.setText("Outros");

        menRelatCli.setText("Clientes");
        menRelatCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelatCliActionPerformed(evt);
            }
        });
        menRelatOut.add(menRelatCli);

        menRelatAtend.setText("Atendentes");
        menRelatAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelatAtendActionPerformed(evt);
            }
        });
        menRelatOut.add(menRelatAtend);

        menuRelat.add(menRelatOut);

        barMenu.add(menuRelat);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(lbMenuPrinc)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lbMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menCadasAgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadasAgendActionPerformed
        CadAgend.gerCadAgend().setVisible(true);
    }//GEN-LAST:event_menCadasAgendActionPerformed

    private void menCadasAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadasAtendActionPerformed
        CadAtend.gerCadAtend().setVisible(true);
    }//GEN-LAST:event_menCadasAtendActionPerformed

    private void menRelatGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelatGeralActionPerformed
        FormGeral.gerFormGeral().setVisible(true);
    }//GEN-LAST:event_menRelatGeralActionPerformed

    private void menCadasClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadasClientActionPerformed
        CadCliente.gerCadCli().setVisible(true);
    }//GEN-LAST:event_menCadasClientActionPerformed

    private void menRelatCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelatCliActionPerformed
        FormCliente.gerCadCli().setVisible(true);
    }//GEN-LAST:event_menRelatCliActionPerformed

    private void menRelatAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelatAtendActionPerformed
        FormAtendente.gerFormAtend().setVisible(true);
    }//GEN-LAST:event_menRelatAtendActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JLabel lbMenuPrinc;
    private javax.swing.JMenuItem menCadasAgend;
    private javax.swing.JMenuItem menCadasAtend;
    private javax.swing.JMenuItem menCadasClient;
    private javax.swing.JMenuItem menRelatAtend;
    private javax.swing.JMenuItem menRelatCli;
    private javax.swing.JMenuItem menRelatGeral;
    private javax.swing.JMenu menRelatOut;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuRelat;
    // End of variables declaration//GEN-END:variables
}
